#!/usr/bin/env bash
BLANK='#28282800'        # Transparent Gruvbox background (Dark0 + 00 alpha)
CLEAR='#92837422'        # Inactive ring (Gruvbox Gray + low alpha)
DEFAULT='#ebdbb2cc'      # Default ring color (Gruvbox Light1 + 80% alpha)
TEXT='#ebdbb2ff'         # Time/Date/Text color (Gruvbox Light1, opaque)
WRONG='#fb4934cc'        # Wrong password (Gruvbox Red + 80% alpha)
VERIFYING='#b8bb26cc'    # Verifying ring (Gruvbox Green + 80% alpha)

PICTURE=/tmp/i3lock.png
SCREENSHOT="scrot -z $PICTURE"

BLUR="5x4"

$SCREENSHOT
magick $PICTURE -blur $BLUR $PICTURE
i3lock -i $PICTURE \
--insidever-color=$CLEAR     \
--ringver-color=$VERIFYING   \
\
--insidewrong-color=$CLEAR   \
--ringwrong-color=$WRONG     \
\
--inside-color=$BLANK        \
--ring-color=$DEFAULT        \
--line-color=$BLANK          \
--separator-color=$DEFAULT   \
\
--verif-color=$TEXT          \
--wrong-color=$TEXT          \
--time-color=$TEXT           \
--date-color=$TEXT           \
--layout-color=$TEXT         \
--keyhl-color=$WRONG         \
--bshl-color=$WRONG          \
\
--clock                      \
--indicator                  \
--time-str="%H:%M:%S"        \
--date-str="%A, %Y-%m-%d"    \

rm $PICTURE
