#!/usr/bin/env bash

BLANK='#28282800'        # Transparent Gruvbox background
CLEAR='#92837422'        # Inactive ring
DEFAULT='#ebdbb2cc'      # Default ring
TEXT='#ebdbb2ff'         # Text color
WRONG='#fb4934cc'        # Wrong password
VERIFYING='#b8bb26cc'    # Verifying
TYPING='#076678cc'       # Typing highlight

swaylock \
  --font "FiraCode Nerd Font"     \
  \
  --screenshots                   \
  --effect-blur 8x5               \
  --effect-vignette 0.4:0.6       \
  \
  --inside-ver-color=$CLEAR       \
  --ring-ver-color=$VERIFYING     \
  \
  --inside-wrong-color=$CLEAR     \
  --ring-wrong-color=$WRONG       \
  \
  --inside-color=$BLANK           \
  --ring-color=$DEFAULT           \
  --line-color=$BLANK             \
  --separator-color=$DEFAULT      \
  \
  --text-ver-color=$TEXT          \
  --text-wrong-color=$TEXT        \
  --text-color=$TEXT              \
  --layout-text-color=$TEXT       \
  --key-hl-color=$TYPING          \
  --bs-hl-color=$WRONG            \
  \
  --clock \
  --indicator \
  --indicator-radius 80 \
  --indicator-thickness 8 \
  --timestr "%H:%M:%S" \
  --datestr "%A, %Y-%m-%d"
