#!/bin/bash

symbol=$(unipicker --command 'rofi -dmenu -p "Unicode" -config ~/.config/rofi/rofidmenu.rasi' | head -n 1)
if [ -n "$symbol" ]; then
    printf "%s" "$symbol" | wl-copy
    # wtype "$symbol" # alternative for Wayland
fi
