[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
decorations = "None" 
opacity = 1.0
title = "Terminal"
padding = {x = 0, y = 0}

[font]
normal = { family = "FiraCode Nerd Font", style = "Light" }

[cursor]
style = { shape = "Underline" , blinking = "Always" }
vi_mode_style = { shape = "Block", blinking = "Always" }

[colors.primary]
foreground = "#e2cca9"
background = "#141617"

[colors.normal]
black = "#181818"
red = "#f2594b"
green = "#b0b846"
yellow = "#e9b143" 
blue = "#80aa9e"
magenta = "#d3869b"
cyan = "#8bba7f"
white = "#FFFFFF"
